function D = D_mat(E,nu)
%D_mat
%    D = D_mat(E,NU)

%    This function was generated by the Symbolic Math Toolbox version 24.2.
%    18-Feb-2025 16:26:19

t2 = E.^2;
t3 = nu.*2.0;
t5 = t3+2.0;
t6 = nu.*t3;
t7 = 1.0./t5;
t8 = nu+t6-1.0;
t9 = E.*t7;
t11 = 1.0./t8;
t10 = t9.*2.0;
t12 = E.*nu.*t11;
t13 = -t12;
t14 = t9+t13;
t15 = t10+t13;
t16 = 1.0./t15;
t18 = nu.*t2.*t7.*t11.*t16.*-2.0;
t19 = t9.*t14.*t16.*4.0;
D = reshape([t19,t18,0.0,t18,t19,0.0,0.0,0.0,t9],[3,3]);
end
