function N = N_gen(xi,eta)
%N_gen
%    N = N_gen(XI,ETA)

%    This function was generated by the Symbolic Math Toolbox version 24.2.
%    23-Jan-2025 19:34:11

t2 = eta+1.0;
t3 = xi+1.0;
t4 = eta-1.0;
t5 = xi-1.0;
N = [(t4.*t5)./4.0,t3.*t4.*(-1.0./4.0),(t2.*t3)./4.0,t2.*t5.*(-1.0./4.0)];
end
