function J_T_det = j_el(xi,eta,in3,in4)
%J_EL
%    J_T_det = J_EL(XI,ETA,IN3,IN4)

%    This function was generated by the Symbolic Math Toolbox version 24.2.
%    23-Jan-2025 19:34:11

x1 = in3(1,:);
x2 = in3(2,:);
x3 = in3(3,:);
x4 = in3(4,:);
y1 = in4(1,:);
y2 = in4(2,:);
y3 = in4(3,:);
y4 = in4(4,:);
t2 = (x2.*y1)./8.0;
t3 = (x1.*y4)./8.0;
t4 = (x2.*y3)./8.0;
t5 = (x3.*y4)./8.0;
t6 = x3.*y2.*(-1.0./8.0);
t7 = x4.*y3.*(-1.0./8.0);
J_T_det = -t2-t3+t4+t5+t6+t7+eta.*t2+eta.*t5+eta.*t7+t3.*xi+t4.*xi+t6.*xi+(x1.*y2)./8.0+(x4.*y1)./8.0-(eta.*x1.*y2)./8.0+(eta.*x1.*y3)./8.0-(eta.*x3.*y1)./8.0-(eta.*x2.*y4)./8.0+(eta.*x4.*y2)./8.0-(x1.*xi.*y3)./8.0+(x3.*xi.*y1)./8.0-(x4.*xi.*y1)./8.0-(x2.*xi.*y4)./8.0+(x4.*xi.*y2)./8.0;
end
