function F = ffun(xi,eta,xn1,xn2,xn3,xn4)
%FFUN
%    F = FFUN(XI,ETA,XN1,XN2,XN3,XN4)

%    This function was generated by the Symbolic Math Toolbox version 24.2.
%    15-Mar-2025 23:15:25

t2 = eta+1.0;
t3 = eta-1.0;
t4 = xi./4.0;
t5 = t4+1.0./4.0;
t6 = t4-1.0./4.0;
F = t2.*t5.*xn3-t3.*t5.*xn2+t3.*t6.*xn1-t2.*t6.*xn4;
end
