function j_det = jfun(xi,eta,xn1,xn2,xn3,xn4,yn1,yn2,yn3,yn4)
%JFUN
%    J_DET = JFUN(XI,ETA,XN1,XN2,XN3,XN4,YN1,YN2,YN3,YN4)

%    This function was generated by the Symbolic Math Toolbox version 24.2.
%    15-Mar-2025 23:15:25

t2 = (xn2.*yn1)./8.0;
t3 = (xn1.*yn4)./8.0;
t4 = (xn2.*yn3)./8.0;
t5 = (xn3.*yn4)./8.0;
t6 = xn3.*yn2.*(-1.0./8.0);
t7 = xn4.*yn3.*(-1.0./8.0);
j_det = -t2-t3+t4+t5+t6+t7+eta.*t2+eta.*t5+eta.*t7+t3.*xi+t4.*xi+t6.*xi+(xn1.*yn2)./8.0+(xn4.*yn1)./8.0-(eta.*xn1.*yn2)./8.0+(eta.*xn1.*yn3)./8.0-(eta.*xn3.*yn1)./8.0-(eta.*xn2.*yn4)./8.0+(eta.*xn4.*yn2)./8.0-(xi.*xn1.*yn3)./8.0+(xi.*xn3.*yn1)./8.0-(xi.*xn4.*yn1)./8.0-(xi.*xn2.*yn4)./8.0+(xi.*xn4.*yn2)./8.0;
end
